// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWS2nV53PoufJC0y_WrJaJNq9kx4kSFaI',
    appId: '1:751113835114:web:1ec5dc3b6abdca4d52f013',
    messagingSenderId: '751113835114',
    projectId: 'mixcall',
    authDomain: 'mixcall.firebaseapp.com',
    storageBucket: 'mixcall.appspot.com',
    measurementId: 'G-PFZFD8LNSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3EewdBdMv87M_WbjQ7oLRX1-cKYY9AM',
    appId: '1:751113835114:android:2c9215d09b6a4c7652f013',
    messagingSenderId: '751113835114',
    projectId: 'mixcall',
    storageBucket: 'mixcall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOb86hlHRH7CQIIfjGoU15zGkwEKHhvk',
    appId: '1:751113835114:ios:1182aed24e9a0e6852f013',
    messagingSenderId: '751113835114',
    projectId: 'mixcall',
    storageBucket: 'mixcall.appspot.com',
    androidClientId: '751113835114-8st260hgl58rafjafmt1v4hmrnm8cl5d.apps.googleusercontent.com',
    iosClientId: '751113835114-r0auk6l8osco05enpmo5s7j795kln9v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMixcallNormaluser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOb86hlHRH7CQIIfjGoU15zGkwEKHhvk',
    appId: '1:751113835114:ios:1182aed24e9a0e6852f013',
    messagingSenderId: '751113835114',
    projectId: 'mixcall',
    storageBucket: 'mixcall.appspot.com',
    androidClientId: '751113835114-8st260hgl58rafjafmt1v4hmrnm8cl5d.apps.googleusercontent.com',
    iosClientId: '751113835114-r0auk6l8osco05enpmo5s7j795kln9v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMixcallNormaluser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWS2nV53PoufJC0y_WrJaJNq9kx4kSFaI',
    appId: '1:751113835114:web:1ec5dc3b6abdca4d52f013',
    messagingSenderId: '751113835114',
    projectId: 'mixcall',
    authDomain: 'mixcall.firebaseapp.com',
    storageBucket: 'mixcall.appspot.com',
    measurementId: 'G-PFZFD8LNSJ',
  );

}